# Generated by Django 6.0.2 on 2026-02-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_notificationread'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Store contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Store contact email', max_length=254)),
                ('address', models.TextField(help_text='Store physical address (will be used for Yandex Maps lookup)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
