# Generated by Django 6.0.2 on 2026-02-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес (RU)'),
        ),
        migrations.AddField(
            model_name='about',
            name='address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil (UZ)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (UZ)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.TextField(blank=True, help_text='Deprecated: use address_uz/ru', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.TextField(help_text='Deprecated: use description_uz/ru'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Deprecated: use title_uz/ru', max_length=200),
        ),
    ]
