# Generated by Django 6.0.2 on 2026-02-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_about_address_ru_about_address_uz_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationread',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='notificationread',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationread',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationRead',
        ),
    ]
