# Generated by Django 6.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Store contact phone number', max_length=20)),
                ('email', models.EmailField(help_text='Store contact email', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Deprecated: use address_uz/ru', null=True)),
                ('address_uz', models.TextField(blank=True, null=True, verbose_name='Manzil (UZ)')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Адрес (RU)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'db_table': 'users_about',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Deprecated: use title_uz/ru', max_length=200)),
                ('description', models.TextField(help_text='Deprecated: use description_uz/ru')),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок (RU)')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание (RU)')),
                ('is_broadcast', models.BooleanField(default=False, help_text='If checked, all users will see this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.ManyToManyField(blank=True, help_text='Select specific users if not a broadcast', related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'users_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_notificationread',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
