# Generated by Django 6.0.2 on 2026-02-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attached to the message', null=True, upload_to='chat_images/'),
        ),
    ]
