# Generated by Django 6.0.2 on 2026-02-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=10)),
                ('items_data', models.JSONField(default=dict, help_text='Order items as JSON')),
                ('notes', models.TextField(blank=True, help_text='Order notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
