# Generated by Django 6.0.2 on 2026-02-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Rasm (Base64)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Rasm (Base64)'),
        ),
    ]
